export const ORDER_PLACE_REQUEST = 'ORDER_PLACE_REQUEST';
export const ORDER_PLACE_SUCCESS = 'ORDER_PLACE_SUCCESS';
export const ORDER_PLACE_FAIL = 'ORDER_PLACE_FAIL';

export const ORDER_GET_REQUEST = 'ORDER_GET_REQUEST';
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS';
export const ORDER_GET_FAIL = 'ORDER_GET_FAIL';
export const ORDER_GET_RESET = 'ORDER_GET_RESET';

export const ORDER_GET_ALL_REQUEST = 'ORDER_GET_ALL_REQUEST';
export const ORDER_GET_ALL_SUCCESS = 'ORDER_GET_ALL_SUCCESS';
export const ORDER_GET_ALL_FAIL = 'ORDER_GET_ALL_FAIL';
export const ORDER_GET_ALL_RESET = 'ORDER_GET_ALL_RESET';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_GET_ALL_REQUEST_ADMIN = 'ORDER_GET_ALL_REQUEST_ADMIN';
export const ORDER_GET_ALL_SUCCESS_ADMIN = 'ORDER_GET_ALL_SUCCESS_ADMIN';
export const ORDER_GET_ALL_FAIL_ADMIN = 'ORDER_GET_ALL_FAIL_ADMIN';
export const ORDER_GET_ALL_RESET_ADMIN = 'ORDER_GET_ALL_RESET_ADMIN';

export const ORDER_DELIVER_REQUEST_ADMIN = 'ORDER_DELIVER_REQUEST_ADMIN';
export const ORDER_DELIVER_SUCCESS_ADMIN = 'ORDER_DELIVER_SUCCESS_ADMIN';
export const ORDER_DELIVER_FAIL_ADMIN = 'ORDER_DELIVER_FAIL_ADMIN';
export const ORDER_DELIVER_RESET_ADMIN = 'ORDER_DELIVER_RESET_ADMIN';
