export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_LIST_RESET = 'PRODUCT_LIST_RESET';

export const PRODUCT_TOP_RATED_LIST_REQUEST = 'PRODUCT_TOP_RATED_LIST_REQUEST';
export const PRODUCT_TOP_RATED_LIST_SUCCESS = 'PRODUCT_TOP_RATED_LIST_SUCCESS';
export const PRODUCT_TOP_RATED_LIST_FAIL = 'PRODUCT_TOP_RATED_LIST_FAIL';
export const PRODUCT_TOP_RATED_LIST_RESET = 'PRODUCT_TOP_RATED_LIST_RESET';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';
export const PRODUCT_DETAIL_RESET = 'PRODUCT_DETAIL_RESET';

export const USER_LIST_RESET_ADMIN = 'USER_LIST_RESET_ADMIN';

export const PRODUCT_DELETE_REQUEST_ADMIN = 'PRODUCT_DELETE_REQUEST_ADMIN';
export const PRODUCT_DELETE_SUCCESS_ADMIN = 'PRODUCT_DELETE_SUCCESS_ADMIN';
export const PRODUCT_DELETE_FAIL_ADMIN = 'PRODUCT_DELETE_FAIL_ADMIN';

export const PRODUCT_CREATE_UPDATE_REQUEST_ADMIN = 'PRODUCT_CREATE_UPDATE_REQUEST_ADMIN';
export const PRODUCT_CREATE_UPDATE_SUCCESS_ADMIN = 'PRODUCT_CREATE_UPDATE_SUCCESS_ADMIN';
export const PRODUCT_CREATE_UPDATE_FAIL_ADMIN = 'PRODUCT_CREATE_UPDATE_FAIL_ADMIN';
export const PRODUCT_CREATE_UPDATE_RESET_ADMIN = 'PRODUCT_CREATE_UPDATE_RESET_ADMIN';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';
