export const SHIPPING_ADDRESS_SAVE_REQUEST = 'SHIPPING_ADDRESS_SAVE_REQUEST';
export const SHIPPING_ADDRESS_SAVE_SUCCESS = 'SHIPPING_ADDRESS_SAVE_SUCCESS';
export const SHIPPING_ADDRESS_SAVE_FAIL = 'SHIPPING_ADDRESS_SAVE_FAIL';