export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET';

export const USER_PROFILE_EDIT_REQUEST = 'USER_PROFILE_EDIT_REQUEST';
export const USER_PROFILE_EDIT_SUCCESS = 'USER_PROFILE_EDIT_SUCCESS';
export const USER_PROFILE_EDIT_FAIL = 'USER_PROFILE_EDIT_FAIL';

export const USER_LIST_REQUEST_ADMIN = 'USER_LIST_REQUEST_ADMIN';
export const USER_LIST_SUCCESS_ADMIN = 'USER_LIST_SUCCESS_ADMIN';
export const USER_LIST_FAIL_ADMIN = 'USER_LIST_FAIL_ADMIN';
export const USER_LIST_RESET_ADMIN = 'USER_LIST_RESET_ADMIN';

export const USER_DELETE_REQUEST_ADMIN = 'USER_DELETE_REQUEST_ADMIN';
export const USER_DELETE_SUCCESS_ADMIN = 'USER_DELETE_SUCCESS_ADMIN';
export const USER_DELETE_FAIL_ADMIN = 'USER_DELETE_FAIL_ADMIN';